"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+=u84c#xgyk$&r$&yo@^l1b)a9ugn5ahih+6#q_#g(w8p9t!04'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False   # ✅ Always False in production

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]  # ✅ Add your domain/hostnames here in production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',   # <-- CustomUser lives here
    'relationship_app',                 # <-- keep this intact
    # 'csp',  # ✅ Uncomment if you install django-csp for Content Security Policy
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'csp.middleware.CSPMiddleware',  # ✅ Uncomment if using django-csp
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (for profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Authentication redirects
LOGIN_REDIRECT_URL = "list_books"   # where users go after login
LOGOUT_REDIRECT_URL = "login"       # where users go after logout

# ✅ Custom User Model
AUTH_USER_MODEL = "bookshelf.CustomUser"


# --- Security Best Practices ---

# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True           # ✅ Force HTTPS for all requests

# Browser protections
SECURE_BROWSER_XSS_FILTER = True     # ✅ Prevent reflected XSS
SECURE_CONTENT_TYPE_NOSNIFF = True   # ✅ Prevent MIME-type sniffing
X_FRAME_OPTIONS = "DENY"             # ✅ Prevent clickjacking

# Secure cookies
CSRF_COOKIE_SECURE = True            # ✅ CSRF cookie only over HTTPS
SESSION_COOKIE_SECURE = True         # ✅ Session cookie only over HTTPS

# HTTP Strict Transport Security (forces HTTPS)
SECURE_HSTS_SECONDS = 31536000       # ✅ 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Content Security Policy (if django-csp is installed)
# CSP_DEFAULT_SRC = ("'self'",)
# CSP_SCRIPT_SRC = ("'self'", "https://trustedscripts.example.com")
# CSP_STYLE_SRC = ("'self'", "https://trustedstyles.example.com")