# Generated by Django 6.0.1 on 2026-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Librarian', 'Librarian')], default='Member', max_length=20),
        ),
    ]
