"""
Serializers for the API application.

Serializers convert model instances to and from Python primitives so
that they can be rendered to JSON or other content types.  They
also provide a convenient place for defining custom validation
rules.
"""
from datetime import date
from rest_framework import serializers
from .models import Author, Book


class BookSerializer(serializers.ModelSerializer):
    """Serialise a ``Book`` instance.

    This serializer exposes all fields on the ``Book`` model.  It
    includes a custom validator for the ``publication_year`` field
    which raises a validation error if the provided year lies in
    the future.  This prevents clients from creating or updating
    books with an unrealistic publication date.
    """

    class Meta:
        model = Book
        # Include all fields.  The ``id`` field is read‑only and
        # automatically generated by Django.
        fields = ['id', 'title', 'publication_year', 'author']

    def validate_publication_year(self, value: int) -> int:
        """Ensure that ``publication_year`` is not in the future.

        Parameters
        ----------
        value : int
            The year provided by the client.

        Returns
        -------
        int
            The same value if it is valid.

        Raises
        ------
        serializers.ValidationError
            If the year is greater than the current calendar year.
        """
        current_year = date.today().year
        if value > current_year:
            raise serializers.ValidationError(
                'Publication year cannot be in the future.'
            )
        return value


class AuthorSerializer(serializers.ModelSerializer):
    """Serialise an ``Author`` along with its nested books.

    By nesting a ``BookSerializer`` within the author serializer and
    marking it as read‑only, the API returns a list of fully
    serialised books when serialising an author.  This demonstrates
    how to handle nested relationships in Django REST Framework.
    """

    # ``many=True`` indicates that an author may have multiple books
    # associated with it.  ``read_only=True`` ensures that the
    # nested books are only used for representation and not for
    # writing; clients must supply a primary key for the author when
    # creating or updating a book via the ``BookSerializer``.
    books = BookSerializer(many=True, read_only=True)

    class Meta:
        model = Author
        fields = ['id', 'name', 'books']
